apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  namespace: monolith 
spec:
  storageClassName: sc  
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pv0001/
