apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: state-postgres
  namespace: monolith
spec:
  serviceName: svc-postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: postgres:10.4
        ports:
        - containerPort: 5432
          name: db
        volumeMounts:
        - name: pv-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: pv-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
      storageClassName: sc