apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: monolith
spec:
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: jmtuset/lc-todo-monolith-psql
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 3000
        envFrom:
          - configMapRef:
              name: env-todo-app
